/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kotlinProject

import org.springframework.boot.SpringApplication
import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.runApplication
import org.springframework.context.ApplicationContext
import org.springframework.core.env.MapPropertySource
import org.springframework.core.env.StandardEnvironment

@SpringBootApplication
open class App

fun main(args: Array<String>) {
    val app = SpringApplication(App::class.java)

//    var env  = StandardEnvironment()
//    var myProps = mutableMapOf<String, Any>()
//    myProps.put("spring.application.name", "myApp")
//    env.systemProperties.put("spring.application.name", "myApp")
//    env.systemEnvironment.put("SPRING_APPLICATION_NAME", "myApp")
//    env.propertySources.addFirst(MapPropertySource("myprops", myProps))
//    app.setEnvironment(env)
    app.run( *args );
}
